---
name: Update

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "45 4 */7 * *"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.head_ref || github.ref }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Workflow keep-alive
        uses: gautamkrishnar/keepalive-workflow@v2

      - name: Update
        run: |
          make clean &&
          make

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            README.md
          base: ${{ github.head_ref }}
          branch: automation
          commit-message: Update README
          delete-branch: true
          title: Update README file
          body:

# vim: set sw=2 sts=2 et :
